# Generated by Django 6.0.1 on 2026-01-28 04:26

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_admin_user(apps, schema_editor):
    User = apps.get_model('core', 'User')
    password = '999999'
    if not User.objects.filter(username='admin').exists():
        User.objects.create(
            username='admin',
            password=make_password(password),
            email='admin@example.com',
            is_superuser=True,
            is_staff=True
        )
    else:
        user = User.objects.get(username='admin')
        user.password = make_password(password)
        user.is_superuser = True
        user.is_staff = True
        user.save()

def reverse_func(apps, schema_editor):
    # We generally don't delete the admin user on reverse to avoid data loss
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_func),
    ]
