# Generated by Django 6.0.1 on 2026-01-28 03:39

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('core', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create(
            username='admin',
            email='admin@example.com',
            password=make_password('999999'),
            is_superuser=True,
            is_staff=True
        )

def reverse_superuser(apps, schema_editor):
    # We don't delete the admin user on reverse to prevent accidental data loss
    # or because it might have been created manually.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_superuser),
    ]
