# Generated by Django 6.0.1 on 2026-01-29 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_in",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
